### ISSUE TITLE
Error while decoding - "Invalid length of decompressed data"

### ISSUE THREAD

**Issue by Krknv** [andr13/amnezia-config-decoder#1]
`$ python3.12 amnezia-config-decoder.py vpn://AAAGX... -o output.json`

```
Traceback (most recent call last):
  File "/Users/user1/amnezia-config-decoder.py", line 84, in <module>
    config = decode_config(args.encoded_string)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user1/amnezia-config-decoder.py", line 39, in decode_config
    raise ValueError("Invalid length of decompressed data")
ValueError: Invalid length of decompressed data
```

**macOS Sonoma 14.5, python v3.12**, использовал код активации для Amnezia Premium

**Comment by andr13** [comment]
> **macOS Sonoma 14.5, python v3.12**, использовал код активации для Amnezia Premium 

К сожалению, у меня нет подписки Amnezia Premium на данный момент. Без неё воспроизвести ошибку попросту невозможно.

**Comment by TheAndrey** [comment]
Я удалил [ненужную проверку](https://github.com/andr13/amnezia-config-decoder/blob/236898031d4ec12c31a7cfa28f3bda9139291bc7/amnezia-config-decoder.py#L38-L39) - всё работает.
